root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  poll = true
  poll_interval = 500
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = true
  rerun_delay = 500

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  enabled = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
